### ISSUE TITLE
Correct broken links in README.md

### ISSUE THREAD

**Issue by nickdex** [nickdex/PasteIt-Chrome#1]
### First Timers Only :new: :hatched_chick: 
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart: [About First Timers Only](http://www.firsttimersonly.com/)

### What you will need to know :thinking:
Nothing. This issue is meant to welcome you to Open Source :blush: I am happy to walk you through the process

### Step by Step :clipboard:

- [x] :raising_hand_woman: **Claim this issue:** Comment below
- [x] :fork_and_knife: **Fork the repository** to have your own copy of this repository by clicking the fork button
- [x] :arrow_down: **Clone the fork** in your machine and **make a separate branch**. Its a good practice to name the branch something like `fix/xxx` or `feature/xxx` where `xxx` is a short description of the changes or feature you are attempting to add
 `$ git clone https://github.com/yourUsername/PasteIt-Chrome.git`
 `$ git checkout -b [name_of_your_new_branch]`
- [x] :memo: **Fix LIBRARIES.md and LICENSE.md links in README.md:**
Replace username by nickdex and appname by PasteIt-Chrome in
`[LIBRARIES](https://github.com/username/appname/blob/master/LIBRARIES.md)` and
`[LICENSE](https://github.com/username/appname/blob/master/LICENSE.md)`
- [x] :ballot_box_with_check: **Check if the links are working:** They should open these two files -
[LIBRARIES](https://github.com/nickdex/PasteIt-Chrome/blob/master/LIBRARIES.md) and [LICENSE](https://github.com/nickdex/PasteIt-Chrome/blob/master/LICENSE.md)
- [x] :floppy_disk: **Commit** your changes with message `Fix #1 Broken links in README.md`
- [x] :arrow_up: **Push the changes** to Github:
 `$ git push origin [name_of_your_new_branch]`
- [x] :twisted_rightwards_arrows: **Start a Pull Request** Set the title to `Broken links in README.md` and set description to `fix nickdex/PasteIt-Chrome#1`. There are two ways how you can start a pull request:
  i. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
  ii. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)
- [x] :checkered_flag: Done :+1: Ask in comments for a review :)

**Comment by gmanideep1991** [comment]
Hello @nickdex , i would like to help with this if its still open.

**Comment by nickdex** [comment]
Hi @gmanideep1991, you are welcome to help out. Follow the steps above and comment here your progress so that I can check them off, same for any doubts that you may have :smile:

**Comment by gmanideep1991** [comment]
Hello @nickdex can you please verify pull request?

**Comment by nickdex** [comment]
@gmanideep1991 Good job, couldn't reply earlier as I was travelling.
